package cn.com.infcn.model.pmodel;

import java.util.Date;

/**
 * 文章表 Tessay generated by 项目开发部
 */
public class Essay implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /***/
    private String id;
    /** 标题 */
    private String title;
    /** 作者 */
    private String author;
    /** 关键字 */
    private String keyWord;
    /** 发布日期 */
    private Date publishtime;
    /** 年 */
    private Integer year;
    /** 全文 */
    private String fullText;
    /** 文章链接 */
    private String titleLink;
    /** 地点 */
    private String addr;
    /** 资源类型 */
    private String resourceCategory;
    /** 资源分类 */
    private String resourceType;
    /** 主题分类一级 */
    private String titleTypeFirst;
    /** 主题分类二级 */
    private String titleTypeSecond;
    /** 岗位 */
    private String position;
    /** 事件 */
    private String event;
    /** 陪同人 */
    private String interviewer;
    /** 参与人 */
    private String related;
    /** 场景 */
    private String scene;

    /***/
    // private Set<TessayParagraph> tessayParagraphs =new
    // HashSet<TessayParagraph>(0);
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getKeyWord() {
        return keyWord;
    }

    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    public Date getPublishtime() {
        return publishtime;
    }

    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    public Integer getYear() {
        return year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    public String getFullText() {
        return fullText;
    }

    public void setFullText(String fullText) {
        this.fullText = fullText;
    }

    public String getTitleLink() {
        return titleLink;
    }

    public void setTitleLink(String titleLink) {
        this.titleLink = titleLink;
    }

    public String getAddr() {
        return addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    public String getResourceCategory() {
        return resourceCategory;
    }

    public void setResourceCategory(String resourceCategory) {
        this.resourceCategory = resourceCategory;
    }

    public String getResourceType() {
        return resourceType;
    }

    public void setResourceType(String resourceType) {
        this.resourceType = resourceType;
    }

    public String getTitleTypeFirst() {
        return titleTypeFirst;
    }

    public void setTitleTypeFirst(String titleTypeFirst) {
        this.titleTypeFirst = titleTypeFirst;
    }

    public String getTitleTypeSecond() {
        return titleTypeSecond;
    }

    public void setTitleTypeSecond(String titleTypeSecond) {
        this.titleTypeSecond = titleTypeSecond;
    }

    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    public String getEvent() {
        return event;
    }

    public void setEvent(String event) {
        this.event = event;
    }

    public String getInterviewer() {
        return interviewer;
    }

    public void setInterviewer(String interviewer) {
        this.interviewer = interviewer;
    }

    public String getRelated() {
        return related;
    }

    public void setRelated(String related) {
        this.related = related;
    }

    public String getScene() {
        return scene;
    }

    public void setScene(String scene) {
        this.scene = scene;
    }

}
