package cn.com.infcn.model.pmodel;

/**
 * 段落表（从文章表中提取） TessayParagraph generated by 项目开发部
 */
public class EssayParagraph implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    /***/
    private String id;
    /** 段落内容 */
    private String paragraphContent;
    /** 段落标记 */
    private Integer paragraphFlag;

    /** 对应文章id */
    // private Essay tessay;
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getParagraphContent() {
        return paragraphContent;
    }

    public void setParagraphContent(String paragraphContent) {
        this.paragraphContent = paragraphContent;
    }

    public Integer getParagraphFlag() {
        return paragraphFlag;
    }

    public void setParagraphFlag(Integer paragraphFlag) {
        this.paragraphFlag = paragraphFlag;
    }

}
